# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b321193ea19e0d19006feb552c854238992236a606107422f7043d34a746320b953057c35774f3bc88aed7392a8bbcb2cb3ff3b77a4595bf674d69b9d831543e

test:
  secret_key_base: 66743d4975007bf11fa8c8e6999db85a1e8eb5591b137273945e014459d723c9d6d051e97ee1a3b7de8f7120586fc1499073794fdeceb04a354e20b1cf342134

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
